
CREATE ROLE readwrite;
GRANT USAGE ON SCHEMA ep_ts to ep_readwrite;
GRANT all ON ALL TABLES IN SCHEMA ep_ts to ep_readwrite;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ep_ts TO ep_readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA ep_ts GRANT ALL ON TABLES TO ep_readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA ep_ts GRANT USAGE, SELECT  ON SEQUENCES TO ep_readwrite;

——————————————————
GRANT ALL on DATABASE postgres to ep_admin
GRANT ALL ON SCHEMA ep_ts to ep_admin;
GRANT ALL ON ALL TABLES IN SCHEMA ep_ts to ep_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA ep_ts TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ep_ts GRANT ALL ON TABLES TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ep_ts GRANT all  ON SEQUENCES TO ep_admin;

GRANT ALL ON SCHEMA hdb_catalog to ep_admin;
GRANT ALL ON ALL TABLES IN SCHEMA hdb_catalog to ep_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA hdb_catalog TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA hdb_catalog GRANT ALL ON TABLES TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA hdb_catalog GRANT all  ON SEQUENCES TO ep_admin;

GRANT ALL ON SCHEMA hdb_views to ep_admin;
GRANT ALL ON ALL TABLES IN SCHEMA hdb_views to ep_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA hdb_views TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA hdb_views GRANT ALL ON TABLES TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA hdb_views GRANT all  ON SEQUENCES TO ep_admin;

GRANT ALL on DATABASE ep_dso to ep_admin;

GRANT ALL ON SCHEMA "OptoPy" to ep_admin;
GRANT ALL ON ALL TABLES IN SCHEMA "OptoPy" to ep_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "OptoPy" TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA "OptoPy" GRANT ALL ON TABLES TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA "OptoPy" GRANT all  ON SEQUENCES TO ep_admin;

GRANT ALL ON SCHEMA ep_cop to ep_admin;
GRANT ALL ON ALL TABLES IN SCHEMA ep_cop to ep_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA ep_cop TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ep_cop GRANT ALL ON TABLES TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA ep_cop GRANT all  ON SEQUENCES TO ep_admin;

GRANT ALL ON SCHEMA public to ep_admin;
GRANT ALL ON ALL TABLES IN SCHEMA public to ep_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ep_admin;
--grant usage to future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ep_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT all  ON SEQUENCES TO ep_admin;
——————————————————


CREATE ROLE readwrite;
GRANT CONNECT ON DATABASE chargeworks TO readwrite;
GRANT USAGE, CREATE ON SCHEMA cw_asset TO readwrite;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cw_asset TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA cw_asset GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA cw_asset TO readwrite;



